import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    './hooks/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#574500',
        'primary-fixed': '#ffe088',
        'tertiary-container': '#97b0ff',
        background: '#fff8f0',
        'on-primary-container': '#554300',
        'surface-variant': '#eae1d4',
        'outline-variant': '#d0c5af',
        outline: '#7f7663',
        'secondary-container': '#ff8484',
        'deep-maroon': '#4A0404',
        'tertiary-fixed-dim': '#b4c5ff',
        'primary-container': '#d4af37',
        secondary: '#a13c3f',
        'surface-dim': '#e1d9cc',
        'on-secondary-container': '#751c22',
        'surface-container-lowest': '#ffffff',
        'earthy-bronze': '#8C6239',
        // Passes 4.5:1 over the hero scrim, where #8C6239 lands at 4.45:1.
        'deep-bronze': '#6B4A22',
        'tertiary-fixed': '#dbe1ff',
        'on-surface-variant': '#4d4635',
        'on-secondary-fixed': '#410007',
        'warm-cream': '#FFFDF5',
        'on-surface': '#1f1b13',
        'on-background': '#1f1b13',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#241a00',
        'surface-container': '#f5eddf',
        surface: '#fff8f0',
        tertiary: '#415ba4',
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#27438a',
        'inverse-primary': '#e9c349',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'surface-container-highest': '#eae1d4',
        'on-tertiary-container': '#254188',
        'primary-fixed-dim': '#e9c349',
        'surface-container-high': '#efe7da',
        'secondary-fixed-dim': '#ffb3b1',
        'on-error': '#ffffff',
        primary: '#735c00',
        'inverse-on-surface': '#f8f0e2',
        'surface-container-low': '#fbf3e5',
        'surface-bright': '#fff8f0',
        'inverse-surface': '#343027',
        'on-tertiary': '#ffffff',
        'surface-tint': '#735c00',
        'secondary-fixed': '#ffdad8',
        'on-secondary-fixed-variant': '#82252a',
        'on-tertiary-fixed': '#00174b',
        success: '#1c6b3c',
        'success-container': '#c8f0d8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        pill: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-mobile': '24px',
        'container-max': '1360px',
        'margin-desktop': '80px',
        gutter: '32px',
      },
      maxWidth: {
        'container-max': '1360px',
      },
      fontFamily: {
        'body-lg': ['var(--font-body)', 'Libre Franklin', 'system-ui', 'sans-serif'],
        'body-md': ['var(--font-body)', 'Libre Franklin', 'system-ui', 'sans-serif'],
        'label-lg': ['var(--font-body)', 'Libre Franklin', 'system-ui', 'sans-serif'],
        'label-sm': ['var(--font-body)', 'Libre Franklin', 'system-ui', 'sans-serif'],
        'headline-lg': ['var(--font-display)', 'Playfair Display', 'Georgia', 'serif'],
        'headline-md': ['var(--font-display)', 'Playfair Display', 'Georgia', 'serif'],
        'display-lg': ['var(--font-display)', 'Playfair Display', 'Georgia', 'serif'],
        'display-lg-mobile': ['var(--font-display)', 'Playfair Display', 'Georgia', 'serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.08em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      keyframes: {
        shimmer: {
          '100%': { transform: 'translateX(100%)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%, 60%': { transform: 'translateX(-4px)' },
          '40%, 80%': { transform: 'translateX(4px)' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        // Exactly half, because the track holds the notices twice: at -50%
        // the second copy sits where the first started, so the reset is
        // invisible and the loop has no seam.
        marquee: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        shimmer: 'shimmer 1.6s infinite',
        shake: 'shake 0.4s ease-in-out',
        'fade-up': 'fade-up 0.5s ease-out both',
        // Slow and linear. Easing would make it surge and stall, and a strip
        // of notices is meant to be read, not watched.
        marquee: 'marquee 45s linear infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
